# Generated by Django 2.2.5 on 2019-09-19 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Swimmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('born', models.DateField()),
            ],
            options={
                'verbose_name': 'Plivač',
                'verbose_name_plural': 'Plivači',
                'db_table': 'Swimmer',
            },
        ),
        migrations.CreateModel(
            name='SwimmingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'verbose_name': 'Grupa',
                'verbose_name_plural': 'Grupe',
                'db_table': 'Group',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_held', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Trening',
                'verbose_name_plural': 'Treninzi',
                'db_table': 'Training',
            },
        ),
        migrations.CreateModel(
            name='TrainingTrainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to=settings.AUTH_USER_MODEL)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swimmingschoolapp.Training')),
            ],
            options={
                'verbose_name': 'TreningTrener',
                'verbose_name_plural': 'TreninziTrener',
                'db_table': 'TrainingTrainer',
            },
        ),
        migrations.CreateModel(
            name='TrainingSwimmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presence', models.BooleanField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swimmingschoolapp.SwimmingGroup')),
                ('swimmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swimmingschoolapp.Swimmer')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swimmingschoolapp.Training')),
            ],
            options={
                'verbose_name': 'TreningPlivač',
                'verbose_name_plural': 'TreninziPlivač',
                'db_table': 'TrainingSwimmer',
            },
        ),
        migrations.AddField(
            model_name='training',
            name='trained_by',
            field=models.ManyToManyField(through='swimmingschoolapp.TrainingTrainer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='swimmer',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swimmers', to='swimmingschoolapp.SwimmingGroup'),
        ),
        migrations.AddField(
            model_name='swimmer',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swimmer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Obavijest',
                'verbose_name_plural': 'Obavijesti',
                'db_table': 'Notification',
            },
        ),
    ]
