# Generated by Django 2.2.5 on 2019-09-20 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swimmingschoolapp', '0002_auto_20190920_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimmer',
            name='parent',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='swimmer', to=settings.AUTH_USER_MODEL),
        ),
    ]
