# Generated by Django 2.2.4 on 2019-09-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimmingschool', '0002_auto_20190908_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='swimminggroup',
            name='name',
            field=models.CharField(default='', max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
